aeto/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),

    path("", include(("dashboards.urls", "dashboards"), namespace="dashboards")),
    
    path("", include(("calendario.urls", "calendario"), namespace="calendario")),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboards/urls.py
# Django
from django.urls import path
from django.views.generic.base import View

# Views
from dashboards.views import views, views_rest, views_pbi

urlpatterns = [
    path(
        route="",
        view=views.HomeView.as_view(),
        name="home"
    ),
    path(
        route="pulpo/",
        view=views.PulpoView.as_view(),
        name="pulpo"
    ),
    path(
        route="api/",
        view=views.VehiculoAPI.as_view(),
        name="api"
    ),
    path(
        route="api/pro/",
        view=views.PulpoProAPI.as_view(),
        name="apiPro"
    ),
    path(
        route="api/tireeye/",
        view=views.TireEyeAPI.as_view(),
        name="apiTireEye"
    ),
    path(
        route="buscar/",
        view=views.buscar,
        name="buscar"
    ),
    path(
        route="config/",
        view=views.ConfigView.as_view(),
        name="config"
    ),
    path(
        route="search/",
        view=views.SearchView.as_view(),
        name="search"
    ),
    path(
        route="api/vehicle_list/",
        view=views_rest.SearchView.as_view(),
        name="api_search"
    ),
    path(
        route="search_id/",
        view=views.search,
        name="search_id"
    ),
    path(
        route="<int:pk>/",
        view=views.DetailView.as_view(),
        name="detail"
    ),
    path(
        route="estatusDeFlota",
        view=views.TireDBView.as_view(),
        name="tireDB1"
    ),
    path(
        route="reemplazoEstimado",
        view=views.TireDB2View.as_view(),
        name="tireDB2"
    ),
    path(
        route="rendimientoDeLlanta",
        view=views.TireDB3View.as_view(),
        name="tireDB3"
    ),
    path(
        route="dashboardOperativo",
        view=views.dashboardOperativoView.as_view(),
        name="dashboardOperativo"
    ),
    path(
        route="vehiculosformulario",
        view=views.vehiculosformularioView.as_view(),
        name="vehiculosformulario"
    ),
    path(
        route="login/",
        view=views.LoginView.as_view(),
        name="login"
    ),
    path(
        route="logout/",
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route="hub",
        view=views.hubView.as_view(),
        name="hub"
    ),
    path(
        route="reporte",
        view=views.ParametroExtractoView.as_view(),
        name="ParametroExtracto"
    ),
    path(
        route="dashboards",
        view=views.SiteMenuView.as_view(),
        name="siteMenu"
    ),
    path(
        route="desechos",
        view=views.catalogoDesechosView.as_view(),
        name="catalogoDesechos"
    ),
    path(
        route="desechos/<int:pk>/",
        view=views.catalogoDesechosEditView.as_view(),
        name="catalogoDesechosEdit"
    ),
    path(
        route="desechos/delete",
        view=views.catalogoDesechosDeleteView,
        name="catalogoDesechosDelete"
    ),
    path(
        route="productos",
        view=views.catalogoProductoView.as_view(),
        name="catalogoProductos"
    ),
    path(
        route="productos/<int:pk>/",
        view=views.catalogoProductoEditView.as_view(),
        name="catalogoProductosEdit"
    ),
    path(
        route="productos/delete",
        view=views.catalogoProductoDeleteView,
        name="catalogoProductoDelete"
    ),
    path(
        route="renovadores",
        view=views.catalogoRenovadoresView.as_view(),
        name="catalogoRenovadores"
    ),
    path(
        route="renovadores/<int:pk>/",
        view=views.catalogoRenovadoresEditView.as_view(),
        name="catalogoRenovadoresEdit"
    ),
    path(
        route="renovadores/delete",
        view=views.catalogoRenovadoresDeleteView,
        name="catalogoRenovadoresDelete"
    ),
    path(
        route="observaciones",
        view=views.catalogoObservacionesView.as_view(),
        name="catalogoObservaciones"
    ),
    path(
        route="observaciones/<int:pk>/",
        view=views.catalogoObservacionesEditView.as_view(),
        name="catalogoObservacionesEdit"
    ),
    path(
        route="observaciones/delete",
        view=views.catalogoObservacionesDeleteView,
        name="catalogoObservacionesDelete"
    ),
    path(
        route="rechazos",
        view=views.catalogoRechazosView.as_view(),
        name="catalogoRechazos"
    ),
    path(
        route="rechazos/<int:pk>/",
        view=views.catalogoRechazosEditView.as_view(),
        name="catalogoRechazosEdit"
    ),
    path(
        route="rechazos/delete",
        view=views.catalogoRechazosDeleteView,
        name="catalogoRechazosDelete"
    ),
    path(
        route="companyFormulario",
        view=views.companyFormularioView.as_view(),
        name="companyFormulario"
    ),
    path(
        route="companyFormulario/<int:pk>/",
        view=views.companyFormularioEditView.as_view(),
        name="companyFormularioEdit"
    ),
    path(
        route="companyFormulario/delete",
        view=views.companyFormularioDeleteView,
        name="companyFormularioDelete"
    ),
     path(
        route="sucursalFormulario",
        view=views.sucursalFormularioView.as_view(),
        name="sucursalFormulario"
    ),
    path(
        route="sucursalFormulario/<int:pk>/",
        view=views.sucursalFormularioEditView.as_view(),
        name="sucursalFormularioEdit"
    ),
    path(
        route="sucursalFormulario/delete",
        view=views.sucursalFormularioDeleteView,
        name="sucursalFormularioDelete"
    ),
    path(
        route="sucursalView",
        view=views.sucursalView.as_view(),
        name="sucursalView"
    ),
    path(
        route="aplicacionesView",
        view=views.aplicacionesView.as_view(),
        name="aplicacionesView"
    ),
    path(
        route="vehiculosView",
        view=views.vehiculosView.as_view(),
        name="vehiculosView"
    ),
    path(
        route="llantasView",
        view=views.llantasView.as_view(),
        name="llantasView"
    ),
    path(
        route="inpeccionesView",
        view=views.inpeccionesView.as_view(),
        name="inspeccionesView"
    ),
    path(
        route="inspeccionesAdd/",
        view=views.my_soap_inspeccion(),
        name="inspeccionesAdd"
    ),
    path(
        route="basesList/",
        view=views.my_soap_base(),
        name="basesList"
    ),
    path(
        route="rutasList/",
        view=views.my_soap_ruta(),
        name="rutasList"
    ),
    path(
        route="vehiculosList/",
        view=views.my_soap_vehiculo(),
        name="vehiculosList"
    ),
    path(
        route="llantasList/",
        view=views.my_soap_llanta(),
        name="llantasList"
    ),
    path(
        route="tallerFormulario",
        view=views.tallerFormularioView.as_view(),
        name="tallerFormulario"
    ),
    path(
        route="tallerFormulario/<int:pk>/",
        view=views.tallerFormularioEditView.as_view(),
        name="tallerFormularioEdit"
    ),
    path(
        route="tallerFormulario/delete",
        view=views.tallerFormularioDeleteView,
        name="tallerFormularioDelete"
    ),
    path(
        route="usuarioFormulario",
        view=views.usuarioFormularioView.as_view(),
        name="usuarioFormulario"
    ),
    path(
        route="usuarioFormulario/<int:pk>/",
        view=views.usuarioFormularioEditView.as_view(),
        name="usuarioFormularioEdit"
    ),
    path(
        route="usuarioFormulario/delete",
        view=views.usuarioFormularioDeleteView,
        name="usuarioFormularioDelete"
    ),
    path(
        route="nuevoVehiculo",
        view=views.nuevoVehiculoView.as_view(),
        name="nuevoVehiculo"
    ),
    path(
        route="nuevoVehiculo/<int:pk>/",
        view=views.nuevoVehiculoEditView.as_view(),
        name="nuevoVehiculoEdit"
    ),
    path(
        route="nuevoVehiculo/delete",
        view=views.nuevoVehiculoDeleteView,
        name="nuevoVehiculoDelete"
    ),
    path(
        route="aplicacionFormulario",
        view=views.aplicacionFormularioView.as_view(),
        name="aplicacionFormulario"
    ),
    path(
        route="aplicacionFormulario/<int:pk>/",
        view=views.aplicacionFormularioEditView.as_view(),
        name="aplicacionFormularioEdit"
    ),
    path(
        route="aplicacionFormulario/delete",
        view=views.aplicacionFormularioDeleteView,
        name="aplicacionFormularioDelete"
    ),
    path(
        route="4umbrales",
        view=views.CuatroUmbralesView.as_view(),
        name="CuatroUmbrales"
    ),
    path(
        route="serialVehiculo",
        view=views.SerialVehiculoView.as_view(),
        name="SerialVehiculo"
    ),
    path(
        route="tireEyeView",
        view=views.TireEyeView.as_view(),
        name="TireEyeView"
    ),
    path(
        route="tireDetail/<int:pk>/",
        view=views.tireDetailView.as_view(),
        name="tireDetail"
    ),
    path(
        route="diagrama/<int:pk>/",
        view=views.diagramaView.as_view(),
        name="diagrama"
    ),
    path(
        route="tireDiagrama/<int:pk>",
        view=views.tireDiagramaView.as_view(),
        name="tireDiagrama"
    ),
    path(
        route="inspeccionLlanta/<int:pk>/",
        view=views.inspeccionLlantaView.as_view(),
        name="inspeccionLlanta"
    ),
    path(
        route="inspeccion-vehiculo/<int:pk>/",
        view=views.inspeccionVehiculo.as_view(),
        name="inspeccionVehiculo"
    ),
    path(
        route="reporteVehiculo/<int:pk>/<str:tipo>",
        view=views.reporteVehiculoView.as_view(),
        name="reporteVehiculo"
    ),
    path(
        route="reporteLlanta/<int:pk>/<int:llanta>/<int:eje>/<int:num_llanta>/<str:pulpo>",
        view=views.reporteLlantaView.as_view(),
        name="reporteLlanta"
    ),
    path(
        route="configuracionVehiculo/<int:pk>/",
        view=views.configuracionVehiculoView.as_view(),
        name="configuracionVehiculo"
    ),
    path(
        route="configuracionLlanta",

templates/webservices/llanta.html
<!DOCTYPE html>
<html lang="es">
<head>
	{% load static %}
	<meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'css/webservices.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/icomoon/style.css' %}"
    />
</head>
	<body>
		<header>
			<h2 class="titulo">WebService Principal</h2>
		</header>
		<main>
			<p>Lista de WebServices</p>
			<nav>
				<li>
					<a href="https://www.aetoweb.com/llantasList/?wsdl">https://www.aetoweb.com/llantasList/?wsdl</a>
				</li>
			</nav>
            <h1>SOAP</h1>
            <code>
                &lt;?xml version="1.0" encoding="utf-8"?&gt; <br>
                &lt;soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"&gt; <br>
                &lt;soap:Body&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&lt;list xmlns="django.soap.example"&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;user&gt;&lt;/user&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&lt;/list&gt; <br>
                &lt;/soap:Body&gt; <br>
                &lt;/soap:Envelope&gt; <br>
            </code>
		</main>
	</body>
</html>
	

templates/webservices/ruta.html
<!DOCTYPE html>
<html lang="es">
<head>
	{% load static %}
	<meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'css/webservices.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/icomoon/style.css' %}"
    />
</head>
	<body>
		<header>
			<h2 class="titulo">WebService Principal</h2>
		</header>
		<main>
			<p>Lista de WebServices</p>
			<nav>
				<li>
					<a href="https://www.aetoweb.com/rutasList/?wsdl">https://www.aetoweb.com/rutasList/?wsdl</a>
				</li>
			</nav>
            <h1>SOAP</h1>
            <code>
                &lt;?xml version="1.0" encoding="utf-8"?&gt; <br>
                &lt;soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"&gt; <br>
                &lt;soap:Body&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&lt;list xmlns="django.soap.example"&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;user&gt;&lt;/user&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&lt;/list&gt; <br>
                &lt;/soap:Body&gt; <br>
                &lt;/soap:Envelope&gt; <br>
            </code>
		</main>
	</body>
</html>
	

templates/webservices/sucursal.html
<!DOCTYPE html>
<html lang="es">
<head>
	{% load static %}
	<meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'css/webservices.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/icomoon/style.css' %}"
    />
</head>
	<body>
		<header>
			<h2 class="titulo">WebService Principal</h2>
		</header>
		<main>
			<p>Lista de WebServices</p>
			<nav>
				<li>
					<a href="https://www.aetoweb.com/basesList/?wsdl">https://www.aetoweb.com/basesList/?wsdl</a>
				</li>
			</nav>
            <h1>SOAP</h1>
            <code>
                &lt;?xml version="1.0" encoding="utf-8"?&gt; <br>
                &lt;soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"&gt; <br>
                &lt;soap:Body&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&lt;list xmlns="django.soap.example"&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;user&gt;&lt;/user&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&lt;/list&gt; <br>
                &lt;/soap:Body&gt; <br>
                &lt;/soap:Envelope&gt; <br>
            </code>
		</main>
	</body>
</html>
	

templates/webservices/vehiculo.html
<!DOCTYPE html>
<html lang="es">
<head>
	{% load static %}
	<meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'css/webservices.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/icomoon/style.css' %}"
    />
</head>
	<body>
		<header>
			<h2 class="titulo">WebService Principal</h2>
		</header>
		<main>
			<p>Lista de WebServices</p>
			<nav>
				<li>
					<a href="https://www.aetoweb.com/vehiculosList/?wsdl">https://www.aetoweb.com/vehiculosList/?wsdl</a>
				</li>
			</nav>
            <h1>SOAP</h1>
            <code>
                &lt;?xml version="1.0" encoding="utf-8"?&gt; <br>
                &lt;soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"&gt; <br>
                &lt;soap:Body&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&lt;list xmlns="django.soap.example"&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;user&gt;&lt;/user&gt; <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&lt;/list&gt; <br>
                &lt;/soap:Body&gt; <br>
                &lt;/soap:Envelope&gt; <br>
            </code>
		</main>
	</body>
</html>
	

templates/webservices/webservices.html
<!DOCTYPE html>
<html lang="es">
<head>
	{% load static %}
	<meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'css/webservices.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/icomoon/style.css' %}"
    />
</head>
	<body>
		<header>
			<h2 class="titulo">WebService Principal</h2>
		</header>
		<main>
			<p>Lista de WebServices</p>
			<nav>
				<li>
					<a href="{% url 'dashboards:inspeccionesView' %}">
						Insert Inspeccion
					</a>
				</li>
				<li>
					<a href="{% url 'dashboards:sucursalView' %}">
						Select Bases
					</a>
				</li>
				<li>
					<a href="{% url 'dashboards:aplicacionesView' %}">
						Select Rutas
					</a>
				</li>
				<li>
					<a href="{% url 'dashboards:vehiculosView' %}">
						Select Vehiculos
					</a>
				</li>
				<li>
					<a href="{% url 'dashboards:llantasView' %}">
						Select Llantas Rodantes
					</a>
				</li>
			</nav>
		</main>
	</body>
</html>
	