aeto/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),

    path("", include(("dashboards.urls", "dashboards"), namespace="dashboards")),
    
    path("", include(("calendario.urls", "calendario"), namespace="calendario")),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboards/urls.py
# Django
from django.urls import path
from django.views.generic.base import View

# Views
from dashboards.views import views, views_rest, views_pbi

urlpatterns = [
    path(
        route="",
        view=views.HomeView.as_view(),
        name="home"
    ),
    path(
        route="pulpo/",
        view=views.PulpoView.as_view(),
        name="pulpo"
    ),
    path(
        route="api/",
        view=views.VehiculoAPI.as_view(),
        name="api"
    ),
    path(
        route="api/pro/",
        view=views.PulpoProAPI.as_view(),
        name="apiPro"
    ),
    path(
        route="api/tireeye/",
        view=views.TireEyeAPI.as_view(),
        name="apiTireEye"
    ),
    path(
        route="buscar/",
        view=views.buscar,
        name="buscar"
    ),
    path(
        route="config/",
        view=views.ConfigView.as_view(),
        name="config"
    ),
    path(
        route="search/",
        view=views.SearchView.as_view(),
        name="search"
    ),
    path(
        route="api/vehicle_list/",
        view=views_rest.SearchView.as_view(),
        name="api_search"
    ),
    path(
        route="search_id/",
        view=views.search,
        name="search_id"
    ),
    path(
        route="<int:pk>/",
        view=views.DetailView.as_view(),
        name="detail"
    ),
    path(
        route="estatusDeFlota",
        view=views.TireDBView.as_view(),
        name="tireDB1"
    ),
    path(
        route="reemplazoEstimado",
        view=views.TireDB2View.as_view(),
        name="tireDB2"
    ),
    path(
        route="rendimientoDeLlanta",
        view=views.TireDB3View.as_view(),
        name="tireDB3"
    ),
    path(
        route="dashboardOperativo",
        view=views.dashboardOperativoView.as_view(),
        name="dashboardOperativo"
    ),
    path(
        route="vehiculosformulario",
        view=views.vehiculosformularioView.as_view(),
        name="vehiculosformulario"
    ),
    path(
        route="login/",
        view=views.LoginView.as_view(),
        name="login"
    ),
    path(
        route="logout/",
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route="hub",
        view=views.hubView.as_view(),
        name="hub"
    ),
    path(
        route="reporte",
        view=views.ParametroExtractoView.as_view(),
        name="ParametroExtracto"
    ),
    path(
        route="dashboards",
        view=views.SiteMenuView.as_view(),
        name="siteMenu"
    ),
    path(
        route="desechos",
        view=views.catalogoDesechosView.as_view(),
        name="catalogoDesechos"
    ),
    path(
        route="desechos/<int:pk>/",
        view=views.catalogoDesechosEditView.as_view(),
        name="catalogoDesechosEdit"
    ),
    path(
        route="desechos/delete",
        view=views.catalogoDesechosDeleteView,
        name="catalogoDesechosDelete"
    ),
    path(
        route="productos",
        view=views.catalogoProductoView.as_view(),
        name="catalogoProductos"
    ),
    path(
        route="productos/<int:pk>/",
        view=views.catalogoProductoEditView.as_view(),
        name="catalogoProductosEdit"
    ),
    path(
        route="productos/delete",
        view=views.catalogoProductoDeleteView,
        name="catalogoProductoDelete"
    ),
    path(
        route="renovadores",
        view=views.catalogoRenovadoresView.as_view(),
        name="catalogoRenovadores"
    ),
    path(
        route="renovadores/<int:pk>/",
        view=views.catalogoRenovadoresEditView.as_view(),
        name="catalogoRenovadoresEdit"
    ),
    path(
        route="renovadores/delete",
        view=views.catalogoRenovadoresDeleteView,
        name="catalogoRenovadoresDelete"
    ),
    path(
        route="observaciones",
        view=views.catalogoObservacionesView.as_view(),
        name="catalogoObservaciones"
    ),
    path(
        route="observaciones/<int:pk>/",
        view=views.catalogoObservacionesEditView.as_view(),
        name="catalogoObservacionesEdit"
    ),
    path(
        route="observaciones/delete",
        view=views.catalogoObservacionesDeleteView,
        name="catalogoObservacionesDelete"
    ),
    path(
        route="rechazos",
        view=views.catalogoRechazosView.as_view(),
        name="catalogoRechazos"
    ),
    path(
        route="rechazos/<int:pk>/",
        view=views.catalogoRechazosEditView.as_view(),
        name="catalogoRechazosEdit"
    ),
    path(
        route="rechazos/delete",
        view=views.catalogoRechazosDeleteView,
        name="catalogoRechazosDelete"
    ),
    path(
        route="companyFormulario",
        view=views.companyFormularioView.as_view(),
        name="companyFormulario"
    ),
    path(
        route="companyFormulario/<int:pk>/",
        view=views.companyFormularioEditView.as_view(),
        name="companyFormularioEdit"
    ),
    path(
        route="companyFormulario/delete",
        view=views.companyFormularioDeleteView,
        name="companyFormularioDelete"
    ),
     path(
        route="sucursalFormulario",
        view=views.sucursalFormularioView.as_view(),
        name="sucursalFormulario"
    ),
    path(
        route="sucursalFormulario/<int:pk>/",
        view=views.sucursalFormularioEditView.as_view(),
        name="sucursalFormularioEdit"
    ),
    path(
        route="sucursalFormulario/delete",
        view=views.sucursalFormularioDeleteView,
        name="sucursalFormularioDelete"
    ),
    path(
        route="sucursalView",
        view=views.sucursalView.as_view(),
        name="sucursalView"
    ),
    path(
        route="aplicacionesView",
        view=views.aplicacionesView.as_view(),
        name="aplicacionesView"
    ),
    path(
        route="vehiculosView",
        view=views.vehiculosView.as_view(),
        name="vehiculosView"
    ),
    path(
        route="llantasView",
        view=views.llantasView.as_view(),
        name="llantasView"
    ),
    path(
        route="inpeccionesView",
        view=views.inpeccionesView.as_view(),
        name="inspeccionesView"
    ),
    path(
        route="inspeccionesAdd/",
        view=views.my_soap_inspeccion(),
        name="inspeccionesAdd"
    ),
    path(
        route="basesList/",
        view=views.my_soap_base(),
        name="basesList"
    ),
    path(
        route="rutasList/",
        view=views.my_soap_ruta(),
        name="rutasList"
    ),
    path(
        route="vehiculosList/",
        view=views.my_soap_vehiculo(),
        name="vehiculosList"
    ),
    path(
        route="llantasList/",
        view=views.my_soap_llanta(),
        name="llantasList"
    ),
    path(
        route="tallerFormulario",
        view=views.tallerFormularioView.as_view(),
        name="tallerFormulario"
    ),
    path(
        route="tallerFormulario/<int:pk>/",
        view=views.tallerFormularioEditView.as_view(),
        name="tallerFormularioEdit"
    ),
    path(
        route="tallerFormulario/delete",
        view=views.tallerFormularioDeleteView,
        name="tallerFormularioDelete"
    ),
    path(
        route="usuarioFormulario",
        view=views.usuarioFormularioView.as_view(),
        name="usuarioFormulario"
    ),
    path(
        route="usuarioFormulario/<int:pk>/",
        view=views.usuarioFormularioEditView.as_view(),
        name="usuarioFormularioEdit"
    ),
    path(
        route="usuarioFormulario/delete",
        view=views.usuarioFormularioDeleteView,
        name="usuarioFormularioDelete"
    ),
    path(
        route="nuevoVehiculo",
        view=views.nuevoVehiculoView.as_view(),
        name="nuevoVehiculo"
    ),
    path(
        route="nuevoVehiculo/<int:pk>/",
        view=views.nuevoVehiculoEditView.as_view(),
        name="nuevoVehiculoEdit"
    ),
    path(
        route="nuevoVehiculo/delete",
        view=views.nuevoVehiculoDeleteView,
        name="nuevoVehiculoDelete"
    ),
    path(
        route="aplicacionFormulario",
        view=views.aplicacionFormularioView.as_view(),
        name="aplicacionFormulario"
    ),
    path(
        route="aplicacionFormulario/<int:pk>/",
        view=views.aplicacionFormularioEditView.as_view(),
        name="aplicacionFormularioEdit"
    ),
    path(
        route="aplicacionFormulario/delete",
        view=views.aplicacionFormularioDeleteView,
        name="aplicacionFormularioDelete"
    ),
    path(
        route="4umbrales",
        view=views.CuatroUmbralesView.as_view(),
        name="CuatroUmbrales"
    ),
    path(
        route="serialVehiculo",
        view=views.SerialVehiculoView.as_view(),
        name="SerialVehiculo"
    ),
    path(
        route="tireEyeView",
        view=views.TireEyeView.as_view(),
        name="TireEyeView"
    ),
    path(
        route="tireDetail/<int:pk>/",
        view=views.tireDetailView.as_view(),
        name="tireDetail"
    ),
    path(
        route="diagrama/<int:pk>/",
        view=views.diagramaView.as_view(),
        name="diagrama"
    ),
    path(
        route="tireDiagrama/<int:pk>",
        view=views.tireDiagramaView.as_view(),
        name="tireDiagrama"
    ),
    path(
        route="inspeccionLlanta/<int:pk>/",
        view=views.inspeccionLlantaView.as_view(),
        name="inspeccionLlanta"
    ),
    path(
        route="inspeccion-vehiculo/<int:pk>/",
        view=views.inspeccionVehiculo.as_view(),
        name="inspeccionVehiculo"
    ),
    path(
        route="reporteVehiculo/<int:pk>/<str:tipo>",
        view=views.reporteVehiculoView.as_view(),
        name="reporteVehiculo"
    ),
    path(
        route="reporteLlanta/<int:pk>/<int:llanta>/<int:eje>/<int:num_llanta>/<str:pulpo>",
        view=views.reporteLlantaView.as_view(),
        name="reporteLlanta"
    ),
    path(
        route="configuracionVehiculo/<int:pk>/",
        view=views.configuracionVehiculoView.as_view(),
        name="configuracionVehiculo"
    ),
    path(
        route="configuracionLlanta",

templates/catalogos-forms/dictamen-form.html
{% if desecho.id %}
  <form action="{% url 'dashboards:catalogoDesechosEdit' desecho.id %}" id="form" class="container" method="POST">
{% else %}
  <form action="{% url 'dashboards:catalogoDesechos' %}" id="form" class="container" method="POST">
{% endif %}
  {% csrf_token %}
  <div class="container-fluid">
    <aside class="form-aeto">

      <!-- Start input -->
      <!-- <div class="form__group field">
        <input
          type="hidden"
          name="id"
          {% if desecho.id %}value="{{desecho.id}}"{% endif %}
        />
        <input
          class="form__field"
          type="text"
          placeholder="llanta"
          name="llanta"
          list="llanta"
          {% if desecho.llanta %}value="{{desecho.llanta}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="llanta" class="form__label">
          Llanta
        </label>
        <datalist id="llanta">
          {% for llanta in llantas %}
            <option value="{{llanta}}">{{llanta}}</option>
          {% endfor %}
        </datalist>
      </div> -->
      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="zona"
          name="zona_de_llanta"
          {% if desecho.zona_de_llanta %}value="{{desecho.zona_de_llanta}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="zona_de_llanta" class="form__label">
          Zona de llanta
        </label>
      </div>
      <!-- End input -->

      <!-- Start input -->
      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="condicion"
          name="condicion"
          {% if desecho.condicion %}value="{{desecho.condicion}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="condicion" class="form__label">
          Condición
        </label>
      </div>
      <!-- End input -->

      <!-- Start input -->
      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="razon"
          name="razon"
          {% if desecho.razon %}value="{{desecho.razon}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="razon" class="form__label">
          Razón
        </label>
      </div>
      <!-- End input -->

    </aside>
  </div>

  <nav class="btn-group">
    {% if desecho.id %}
    
    <button class="btn btn-success">
      <span class="icon-checkmark"></span>
    </button>

    <a href="{% url 'dashboards:catalogoDesechos' %}" class="btn btn-danger">
      <span class="icon-cross"></span>
    </a>

    {% else %}
    <button class="btn btn-success">
      <span class="icon-plus6"></span>
    </button>
    <a href="" class="btn btn-download">
      <span class="icon-download"></span>
    </a>
    {% endif %}
  </nav>
</form>

templates/catalogos-forms/observaciones-form.html
{% if observacion.id %}
  <form action="{% url 'dashboards:catalogoObservacionesEdit' observacion.id %}" id="form" class="container" method="POST">
{% else %}
  <form action="{% url 'dashboards:catalogoObservaciones' %}" id="form" class="container" method="POST">
{% endif %}
  {% csrf_token %}
  <div class="container-fluid">
    <aside class="form-aeto">

      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="llanta"
          name="llanta"
          list="llanta"
          {% if observacion.llanta %}value="{{observacion.llanta}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="llanta" class="form__label">
          Llanta
        </label>
        <datalist id="llanta">
          {% for llanta in llantas %}
            <option value="{{llanta}}">{{llanta}}</option>
          {% endfor %}
        </datalist>
      </div>

      <!-- Start input -->
      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="observacion"
          name="observacion"
          {% if observacion.observacion %}value="{{observacion.observacion}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="observacion" class="form__label">
          Observación
        </label>
      </div>
      <!-- End input -->

      <!-- Start input -->
      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="color"
          name="color"
          list="color"
          {% if observacion.color %}value="{{observacion.color}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="color" class="form__label">
          Color
        </label>
        <datalist id="color">
          <option value="Verde">Verde</option>
          <option value="Amarillo">Amarillo</option>
          <option value="Rojo">Rojo</option>
          <option value="Morado">Morado</option>
        </datalist>
      </div>
      <!-- End input -->
    </aside>
  </div>

  <nav class="btn-group">
    {% if observacion.id %}
    
    <button class="btn btn-success">
      <span class="icon-checkmark"></span>
    </button>

    <a href="{% url 'dashboards:catalogoObservaciones' %}" class="btn btn-danger">
      <span class="icon-cross"></span>
    </a>

    {% else %}
    <button class="btn btn-success">
      <span class="icon-plus6"></span>
    </button>
    <a href="" class="btn btn-download">
      <span class="icon-download"></span>
    </a>
    {% endif %}
  </nav>
</form>

templates/catalogos-forms/productos-form.html
{% if producto.id %}
  <form action="{% url 'dashboards:catalogoProductosEdit' producto.id %}" id="form" class="container" method="POST">
{% else %}
  <form action="{% url 'dashboards:catalogoProductos' %}" id="form" class="container" method="POST">
{% endif %}
  {% csrf_token %}
  <div class="container-fluid">
    <aside class="form-aeto">
      <div class="form__group field">
        <input
          type="hidden"
          name="id"
          {% if producto.id %}value="{{producto.id}}"{% endif %}
        />
        <input
          type="hidden"
          name="compania"
          value="{{compania}}"
        />
        <input
          class="form__field"
          type="text"
          placeholder="Marca..."
          name="marca"
          autocomplete="off"
          {% if producto.marca %}value="{{producto.marca}}"{% endif %}
          id="marca"
          required
        />
        <label for="marca" class="form__label">Marca</label>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="Dibujo..."
          name="dibujo"
          {% if producto.dibujo %}value="{{producto.dibujo}}"{% endif %}
          autocomplete="off"
          id="dibujo"
          required
        />
        <label for="dibujo" class="form__label">Dibujo</label>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="Rango..."
          name="rango"
          id="rango"
          {% if producto.rango %}value="{{producto.rango}}"{% endif %}
          autocomplete="off"
        />
        <label for="rango" class="form__label">Rango</label>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="Dimension..."
          name="dimension"
          id="dimension"
          {% if producto.dimension %}value="{{producto.dimension}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="dimension" class="form__label">Dimension</label>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="producto..."
          name="producto"
          id="producto"
          readonly
          autocomplete="off"
          required
        />
        <label for="producto" class="form__label">Producto</label>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="number"
          placeholder="Profundidad inicial..."
          name="profundidad_inicial"
          {% if producto.profundidad_inicial %}value="{{producto.profundidad_inicial}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="profundidad-inicial" class="form__label">Profundidad inicial</label>
      </div>


      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="Aplicación..."
          name="aplicacion"
          {% if producto.aplicacion %}value="{{producto.aplicacion}}"{% endif %}
          list="aplicacion"
          autocomplete="off"
          required
        />
        <label for="aplicacion" class="form__label">Aplicación</label>
        <datalist id="aplicacion">
          <option value="Dirección">Dirección</option>
          <option value="Tracción">Tracción</option>
          <option value="Arrastre">Arrastre</option>
          <option value="Mixta">Mixta</option>
          <option value="Regional">Regional</option>
          <option value="Urbano">Urbano</option>
        </datalist>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="Vida..."
          name="vida"
          {% if producto.vida %}value="{{producto.vida}}"{% endif %}
          list="vida"
          autocomplete="off"
          required
        />
        <label for="vida" class="form__label">Vida</label>
        <datalist id="vida">
          <option value="Nueva">Nueva</option>
          <option value="Renovada">Renovada</option>
          <option value="Vitacasco">Vitacasco</option>
        </datalist>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="number"
          placeholder="Precio actual..."
          name="precio"
          {% if producto.precio %}value="{{producto.precio}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="precio" class="form__label">Precio actual</label>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="number"
          placeholder="KM esperado..."
          name="km_esperado"
          {% if producto.km_esperado %}value="{{producto.km_esperado}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="km" class="form__label">KM esperado</label>
      </div>
    </aside>
  </div>

  <nav class="btn-group">
    {% if producto.id %}
    
    <button class="btn btn-success">
      <span class="icon-checkmark"></span>
    </button>

    <a href="{% url 'dashboards:catalogoProductos' %}" class="btn btn-danger">
      <span class="icon-cross"></span>
    </a>

    {% else %}
    <button class="btn btn-success">
      <span class="icon-plus6"></span>
    </button>
    <a href="" class="btn btn-download">
      <span class="icon-download"></span>
    </a>
    {% endif %}
  </nav>
</form>

templates/catalogos-forms/rechazo-form.html
{% if rechazo.id %}
  <form action="{% url 'dashboards:catalogoRechazosEdit' rechazo.id %}" id="form" class="container" method="POST">
{% else %}
  <form action="{% url 'dashboards:catalogoRechazos' %}" id="form" class="container" method="POST">
{% endif %}
  {% csrf_token %}
  <div class="container-fluid">
    <aside class="form-aeto">

      <div class="form__group field">
        <input
          type="hidden"
          name="id"
          {% if rechazo.id %}value="{{rechazo.id}}"{% endif %}
        />
        <input
          class="form__field"
          type="text"
          placeholder="compania"
          name="compania"
          list="compania"
          {% if rechazo.compania %}value="{{rechazo.compania}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="compania" class="form__label">
          Compania
        </label>
        <datalist id="compania">
          {% for compania in companias %}
            <option value="{{compania}}">{{compania}}</option>
          {% endfor %}
        </datalist>
      </div>

      <!-- Start input -->
      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="razon"
          name="razon"
          {% if rechazo.razon %}value="{{rechazo.razon}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="razon" class="form__label">
          Razón
        </label>
      </div>
      <!-- End input -->

    </aside>
  </div>

  <nav class="btn-group">
    {% if rechazo.id %}
    
    <button class="btn btn-success">
      <span class="icon-checkmark"></span>
    </button>

    <a href="{% url 'dashboards:catalogoRechazos' %}" class="btn btn-danger">
      <span class="icon-cross"></span>
    </a>

    {% else %}
    <button class="btn btn-success">
      <span class="icon-plus6"></span>
    </button>
    <a href="" class="btn btn-download">
      <span class="icon-download"></span>
    </a>
    {% endif %}
  </nav>
</form>

templates/catalogos-forms/renovadores-form.html
{% if renovador.id %}
  <form action="{% url 'dashboards:catalogoRenovadoresEdit' renovador.id %}" id="form" class="container" method="POST">
{% else %}
  <form action="{% url 'dashboards:catalogoRenovadores' %}" id="form" class="container" method="POST">
{% endif %}
  {% csrf_token %}
  <div class="container-fluid">
    <aside class="form-aeto">
      <div class="form__group field">
        <input
          type="hidden"
          name="id"
          {% if renovador.id %}value="{{renovador.id}}"{% endif %}
        />
        <input
          class="form__field"
          type="text"
          placeholder="nombre"
          name="nombre"
          {% if renovador.nombre %}value="{{renovador.nombre}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="nombre" class="form__label">
          Nombre
        </label>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="ciudad"
          name="ciudad"
          {% if renovador.ciudad %}value="{{renovador.ciudad}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="ciudad" class="form__label">
          Ciudad
        </label>
      </div>

      <div class="form__group field">
        <input
          class="form__field"
          type="text"
          placeholder="Marca"
          name="marca"
          {% if renovador.marca %}value="{{renovador.marca}}"{% endif %}
          autocomplete="off"
          required
        />
        <label for="marca" class="form__label">Marca</label>
      </div>

    </aside>
  </div>

  <nav class="btn-group">
    {% if renovador.id %}
    
    <button class="btn btn-success">
      <span class="icon-checkmark"></span>
    </button>

    <a href="{% url 'dashboards:catalogoRenovadores' %}" class="btn btn-danger">
      <span class="icon-cross"></span>
    </a>

    {% else %}
    <button class="btn btn-success">
      <span class="icon-plus6"></span>
    </button>
    <a href="" class="btn btn-download">
      <span class="icon-download"></span>
    </a>
    {% endif %}
  </nav>
</form>