aeto/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),

    path("", include(("dashboards.urls", "dashboards"), namespace="dashboards")),
    
    path("", include(("calendario.urls", "calendario"), namespace="calendario")),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboards/urls.py
# Django
from django.urls import path
from django.views.generic.base import View

# Views
from dashboards.views import views, views_rest, views_pbi

urlpatterns = [
    path(
        route="",
        view=views.HomeView.as_view(),
        name="home"
    ),
    path(
        route="pulpo/",
        view=views.PulpoView.as_view(),
        name="pulpo"
    ),
    path(
        route="api/",
        view=views.VehiculoAPI.as_view(),
        name="api"
    ),
    path(
        route="api/pro/",
        view=views.PulpoProAPI.as_view(),
        name="apiPro"
    ),
    path(
        route="api/tireeye/",
        view=views.TireEyeAPI.as_view(),
        name="apiTireEye"
    ),
    path(
        route="buscar/",
        view=views.buscar,
        name="buscar"
    ),
    path(
        route="config/",
        view=views.ConfigView.as_view(),
        name="config"
    ),
    path(
        route="search/",
        view=views.SearchView.as_view(),
        name="search"
    ),
    path(
        route="api/vehicle_list/",
        view=views_rest.SearchView.as_view(),
        name="api_search"
    ),
    path(
        route="search_id/",
        view=views.search,
        name="search_id"
    ),
    path(
        route="<int:pk>/",
        view=views.DetailView.as_view(),
        name="detail"
    ),
    path(
        route="estatusDeFlota",
        view=views.TireDBView.as_view(),
        name="tireDB1"
    ),
    path(
        route="reemplazoEstimado",
        view=views.TireDB2View.as_view(),
        name="tireDB2"
    ),
    path(
        route="rendimientoDeLlanta",
        view=views.TireDB3View.as_view(),
        name="tireDB3"
    ),
    path(
        route="dashboardOperativo",
        view=views.dashboardOperativoView.as_view(),
        name="dashboardOperativo"
    ),
    path(
        route="vehiculosformulario",
        view=views.vehiculosformularioView.as_view(),
        name="vehiculosformulario"
    ),
    path(
        route="login/",
        view=views.LoginView.as_view(),
        name="login"
    ),
    path(
        route="logout/",
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route="hub",
        view=views.hubView.as_view(),
        name="hub"
    ),
    path(
        route="reporte",
        view=views.ParametroExtractoView.as_view(),
        name="ParametroExtracto"
    ),
    path(
        route="dashboards",
        view=views.SiteMenuView.as_view(),
        name="siteMenu"
    ),
    path(
        route="desechos",
        view=views.catalogoDesechosView.as_view(),
        name="catalogoDesechos"
    ),
    path(
        route="desechos/<int:pk>/",
        view=views.catalogoDesechosEditView.as_view(),
        name="catalogoDesechosEdit"
    ),
    path(
        route="desechos/delete",
        view=views.catalogoDesechosDeleteView,
        name="catalogoDesechosDelete"
    ),
    path(
        route="productos",
        view=views.catalogoProductoView.as_view(),
        name="catalogoProductos"
    ),
    path(
        route="productos/<int:pk>/",
        view=views.catalogoProductoEditView.as_view(),
        name="catalogoProductosEdit"
    ),
    path(
        route="productos/delete",
        view=views.catalogoProductoDeleteView,
        name="catalogoProductoDelete"
    ),
    path(
        route="renovadores",
        view=views.catalogoRenovadoresView.as_view(),
        name="catalogoRenovadores"
    ),
    path(
        route="renovadores/<int:pk>/",
        view=views.catalogoRenovadoresEditView.as_view(),
        name="catalogoRenovadoresEdit"
    ),
    path(
        route="renovadores/delete",
        view=views.catalogoRenovadoresDeleteView,
        name="catalogoRenovadoresDelete"
    ),
    path(
        route="observaciones",
        view=views.catalogoObservacionesView.as_view(),
        name="catalogoObservaciones"
    ),
    path(
        route="observaciones/<int:pk>/",
        view=views.catalogoObservacionesEditView.as_view(),
        name="catalogoObservacionesEdit"
    ),
    path(
        route="observaciones/delete",
        view=views.catalogoObservacionesDeleteView,
        name="catalogoObservacionesDelete"
    ),
    path(
        route="rechazos",
        view=views.catalogoRechazosView.as_view(),
        name="catalogoRechazos"
    ),
    path(
        route="rechazos/<int:pk>/",
        view=views.catalogoRechazosEditView.as_view(),
        name="catalogoRechazosEdit"
    ),
    path(
        route="rechazos/delete",
        view=views.catalogoRechazosDeleteView,
        name="catalogoRechazosDelete"
    ),
    path(
        route="companyFormulario",
        view=views.companyFormularioView.as_view(),
        name="companyFormulario"
    ),
    path(
        route="companyFormulario/<int:pk>/",
        view=views.companyFormularioEditView.as_view(),
        name="companyFormularioEdit"
    ),
    path(
        route="companyFormulario/delete",
        view=views.companyFormularioDeleteView,
        name="companyFormularioDelete"
    ),
     path(
        route="sucursalFormulario",
        view=views.sucursalFormularioView.as_view(),
        name="sucursalFormulario"
    ),
    path(
        route="sucursalFormulario/<int:pk>/",
        view=views.sucursalFormularioEditView.as_view(),
        name="sucursalFormularioEdit"
    ),
    path(
        route="sucursalFormulario/delete",
        view=views.sucursalFormularioDeleteView,
        name="sucursalFormularioDelete"
    ),
    path(
        route="sucursalView",
        view=views.sucursalView.as_view(),
        name="sucursalView"
    ),
    path(
        route="aplicacionesView",
        view=views.aplicacionesView.as_view(),
        name="aplicacionesView"
    ),
    path(
        route="vehiculosView",
        view=views.vehiculosView.as_view(),
        name="vehiculosView"
    ),
    path(
        route="llantasView",
        view=views.llantasView.as_view(),
        name="llantasView"
    ),
    path(
        route="inpeccionesView",
        view=views.inpeccionesView.as_view(),
        name="inspeccionesView"
    ),
    path(
        route="inspeccionesAdd/",
        view=views.my_soap_inspeccion(),
        name="inspeccionesAdd"
    ),
    path(
        route="basesList/",
        view=views.my_soap_base(),
        name="basesList"
    ),
    path(
        route="rutasList/",
        view=views.my_soap_ruta(),
        name="rutasList"
    ),
    path(
        route="vehiculosList/",
        view=views.my_soap_vehiculo(),
        name="vehiculosList"
    ),
    path(
        route="llantasList/",
        view=views.my_soap_llanta(),
        name="llantasList"
    ),
    path(
        route="tallerFormulario",
        view=views.tallerFormularioView.as_view(),
        name="tallerFormulario"
    ),
    path(
        route="tallerFormulario/<int:pk>/",
        view=views.tallerFormularioEditView.as_view(),
        name="tallerFormularioEdit"
    ),
    path(
        route="tallerFormulario/delete",
        view=views.tallerFormularioDeleteView,
        name="tallerFormularioDelete"
    ),
    path(
        route="usuarioFormulario",
        view=views.usuarioFormularioView.as_view(),
        name="usuarioFormulario"
    ),
    path(
        route="usuarioFormulario/<int:pk>/",
        view=views.usuarioFormularioEditView.as_view(),
        name="usuarioFormularioEdit"
    ),
    path(
        route="usuarioFormulario/delete",
        view=views.usuarioFormularioDeleteView,
        name="usuarioFormularioDelete"
    ),
    path(
        route="nuevoVehiculo",
        view=views.nuevoVehiculoView.as_view(),
        name="nuevoVehiculo"
    ),
    path(
        route="nuevoVehiculo/<int:pk>/",
        view=views.nuevoVehiculoEditView.as_view(),
        name="nuevoVehiculoEdit"
    ),
    path(
        route="nuevoVehiculo/delete",
        view=views.nuevoVehiculoDeleteView,
        name="nuevoVehiculoDelete"
    ),
    path(
        route="aplicacionFormulario",
        view=views.aplicacionFormularioView.as_view(),
        name="aplicacionFormulario"
    ),
    path(
        route="aplicacionFormulario/<int:pk>/",
        view=views.aplicacionFormularioEditView.as_view(),
        name="aplicacionFormularioEdit"
    ),
    path(
        route="aplicacionFormulario/delete",
        view=views.aplicacionFormularioDeleteView,
        name="aplicacionFormularioDelete"
    ),
    path(
        route="4umbrales",
        view=views.CuatroUmbralesView.as_view(),
        name="CuatroUmbrales"
    ),
    path(
        route="serialVehiculo",
        view=views.SerialVehiculoView.as_view(),
        name="SerialVehiculo"
    ),
    path(
        route="tireEyeView",
        view=views.TireEyeView.as_view(),
        name="TireEyeView"
    ),
    path(
        route="tireDetail/<int:pk>/",
        view=views.tireDetailView.as_view(),
        name="tireDetail"
    ),
    path(
        route="diagrama/<int:pk>/",
        view=views.diagramaView.as_view(),
        name="diagrama"
    ),
    path(
        route="tireDiagrama/<int:pk>",
        view=views.tireDiagramaView.as_view(),
        name="tireDiagrama"
    ),
    path(
        route="inspeccionLlanta/<int:pk>/",
        view=views.inspeccionLlantaView.as_view(),
        name="inspeccionLlanta"
    ),
    path(
        route="inspeccion-vehiculo/<int:pk>/",
        view=views.inspeccionVehiculo.as_view(),
        name="inspeccionVehiculo"
    ),
    path(
        route="reporteVehiculo/<int:pk>/<str:tipo>",
        view=views.reporteVehiculoView.as_view(),
        name="reporteVehiculo"
    ),
    path(
        route="reporteLlanta/<int:pk>/<int:llanta>/<int:eje>/<int:num_llanta>/<str:pulpo>",
        view=views.reporteLlantaView.as_view(),
        name="reporteLlanta"
    ),
    path(
        route="configuracionVehiculo/<int:pk>/",
        view=views.configuracionVehiculoView.as_view(),
        name="configuracionVehiculo"
    ),
    path(
        route="configuracionLlanta",

dashboards/forms/multiple_forms.py
from django.views.generic.base import View, TemplateResponseMixin
from django.views.generic.edit import FormMixin, ProcessFormView


class MultipleFormsMixin(FormMixin):
    """
    A mixin that provides a way to show and handle several forms in a
    request.
    """
    form_classes = {} # set the form classes as a mapping

    def get_form_classes(self):
        return self.form_classes

    def get_forms(self, form_classes):
        return dict([(key, klass(**self.get_form_kwargs())) \
            for key, klass in form_classes.items()])

    def forms_valid(self, forms):
        return super(MultipleFormsMixin, self).form_valid(forms)

    def forms_invalid(self, forms):
        return self.render_to_response(self.get_context_data(forms=forms))


class ProcessMultipleFormsView(ProcessFormView):
    """
    A mixin that processes multiple forms on POST. Every form must be
    valid.
    """
    def get(self, request, *args, **kwargs):
        form_classes = self.get_form_classes()
        forms = self.get_forms(form_classes)
        return self.render_to_response(self.get_context_data(forms=forms))

    def post(self, request, *args, **kwargs):
        form_classes = self.get_form_classes()
        forms = self.get_forms(form_classes)
        if all([form.is_valid() for form in forms.values()]):
            return self.forms_valid(forms)
        else:
            return self.forms_invalid(forms)


class BaseMultipleFormsView(MultipleFormsMixin, ProcessMultipleFormsView):
    """
    A base view for displaying several forms.
    """

class MultipleFormsView(TemplateResponseMixin, BaseMultipleFormsView):
    """
    A view for displaing several forms, and rendering a template response.
    """

templates/formularios/forms/form-aplicacion.html
<!-- Start input -->
<div class="form__group field">
  <input
    type="hidden"
    name="id"
    {% if aplicacion.id %}value="{{aplicacion.id}}"{% endif %}
  />
  <input
    class="form__field"
    type="text"
    placeholder="nombre"
    name="nombre"
    {% if aplicacion.nombre %}value="{{aplicacion.nombre}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="nombre" class="form__label">
    Nombre
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<!-- <div class="form__group field">
  <input
    class="form__field"
    type="text"
    placeholder="company"
    name="compania"
    list="company"
    {% if aplicacion.compania %}value="{{aplicacion.compania}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="company" class="form__label">
    Compañia
  </label>
  <datalist id="company">
    {% for compania in companias %}
      <option value="{{compania}}">{{compania}}</option>
    {% endfor %}
  </datalist>
</div> -->
<!-- End input -->

<label for="compania" class="select-label">Compañia</label>
<select name="compania" id="compania" required class="select-input">
  <option value="">Seleccione una compañia...</option>
  {% if aplicacion.compania %}<option value="{{aplicacion.compania}}" selected>{{aplicacion.compania}}</option>{% endif %}
  {% for compania in companias %}
    <option value="{{compania}}">{{compania}}</option>
  {% endfor %}
</select>

<!-- Start input -->
<!-- <div class="form__group field">
  <input
    class="form__field"
    type="text"
    placeholder="sucursal"
    name="ubicacion"
    list="sucursal"
    {% if aplicacion.ubicacion %}value="{{aplicacion.ubicacion}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="sucursal" class="form__label">
    Sucursal
  </label>
  <datalist id="sucursal">
    {% for sucursal in sucursales %}
      <option value="{{sucursal}}">{{sucursal}}</option>
    {% endfor %}
  </datalist>
</div> -->
<!-- End input -->

<label for="sucursal" class="select-label">Sucursal</label>
<select name="ubicacion" id="sucursal" required class="select-input">
  <option value="">Seleccione una sucursal...</option>
  {% if aplicacion.sucursal %}<option value="{{aplicacion.sucursal}}" selected>{{aplicacion.sucursal}}</option>{% endif %}
  {% for sucursal in sucursales %}
    <option value="{{sucursal}}">{{sucursal}}</option>
  {% endfor %}
</select>

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="parametro_desgaste_direccion"
    name="parametro_desgaste_direccion"
    {% if aplicacion.parametro_desgaste_direccion %}value="{{aplicacion.parametro_desgaste_direccion}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="sucursal" class="form__label">
    Parámetro de desgaste de dirección
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="parametro_desgaste_traccion"
    name="parametro_desgaste_traccion"
    {% if aplicacion.parametro_desgaste_traccion %}value="{{aplicacion.parametro_desgaste_traccion}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="sucursal" class="form__label">
    Parámetro de desgaste de traccion
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="parametro_desgaste_arrastre"
    name="parametro_desgaste_arrastre"
    {% if aplicacion.parametro_desgaste_arrastre %}value="{{aplicacion.parametro_desgaste_arrastre}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="sucursal" class="form__label">
    Parámetro de desgaste de arrastre
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="parametro_desgaste_loco"
    name="parametro_desgaste_loco"
    {% if aplicacion.parametro_desgaste_loco %}value="{{aplicacion.parametro_desgaste_loco}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="sucursal" class="form__label">
    Parámetro de desgaste de loco
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="parametro_desgaste_retractil"
    name="parametro_desgaste_retractil"
    {% if aplicacion.parametro_desgaste_retractil %}value="{{aplicacion.parametro_desgaste_retractil}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="sucursal" class="form__label">
    Parámetro de desgaste de retractil
  </label>
</div>
<!-- End input -->

templates/formularios/forms/form-sucursal.html
<!-- Start input -->
<div class="form__group field">
  <input
    type="hidden"
    name="id"
    {% if sucursal.id %}value="{{sucursal.id}}"{% endif %}
  />
  <input
    class="form__field"
    type="text"
    placeholder="nombre"
    name="nombre"
    {% if sucursal.nombre %}value="{{sucursal.nombre}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="nombre" class="form__label">
    Nombre
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<!-- <div class="form__group field">
  <input
    class="form__field"
    type="text"
    placeholder="compania"
    name="compania"
    list="compania"
    autocomplete="off"
    required
  />
  <label for="compania" class="form__label">
    Compañia
  </label>
  <datalist id="compania">
    
  </datalist>
</div> -->
<!-- End input -->

<label for="compania" class="select-label">Compañia</label>
<select name="compania" id="compania" required class="select-input">
  <option value="">Seleccione una compañia...</option>
  {% if sucursal.compania %}<option value="{{sucursal.compania}}" selected></option>{% endif %}
  {% for compania in companias %}
    <option value="{{compania}}">{{compania}}</option>
  {% endfor %}
</select>

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="rendimiento de nueva a 1r"
    name="rendimiento_de_nueva"
    {% if sucursal.rendimiento_de_nueva %}value="{{sucursal.rendimiento_de_nueva}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="rendimiento_de_nueva" class="form__label">
    Rendimiento de nueva a 1R
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="rendimiento de 1r a 2r"
    name="rendimiento_de_primera"
    {% if sucursal.rendimiento_de_primera %}value="{{sucursal.rendimiento_de_primera}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="rendimiento_de_primera" class="form__label">
    Rendimiento de 1R a 2R
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="rendimiento de 2r a 3r"
    name="rendimiento_de_segunda"
    {% if sucursal.rendimiento_de_segunda %}value="{{sucursal.rendimiento_de_segunda}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="rendimiento_de_segunda" class="form__label">
    Rendimiento de 2R a 3R
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="rendimiento de 3r a 4r"
    name="rendimiento_de_tercera"
    {% if sucursal.rendimiento_de_tercera %}value="{{sucursal.rendimiento_de_tercera}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="rendimiento_de_tercera" class="form__label">
    Rendimiento de 3R a 4R
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="rendimiento de 4r a 5r"
    name="rendimiento_de_cuarta"
    {% if sucursal.rendimiento_de_cuarta %}value="{{sucursal.rendimiento_de_cuarta}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="rendimiento_de_cuarta" class="form__label">
    Rendimiento de 4R a 5R
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="precio promedio de llanta direccion"
    name="precio_nueva_direccion"
    {% if sucursal.precio_nueva_direccion %}value="{{sucursal.precio_nueva_direccion}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="precio_nueva_direccion" class="form__label">
    Precio promedio de llanta direccion
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="precio promedio de llanta nueva"
    name="precio_nueva"
    {% if sucursal.precio_nueva %}value="{{sucursal.precio_nueva}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="precio_nueva" class="form__label">
    precio promedio de llanta nueva
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="number"
    placeholder="precio promedio de llanta renovada"
    name="precio_renovada"
    {% if sucursal.precio_renovada %}value="{{sucursal.precio_renovada}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="precio_renovada" class="form__label">
    Precio promedio de llanta renovada
  </label>
</div>
<!-- End input -->

<nav class="flex-row">
  {% if sucursal.id %}
  <button class="btn btn-success">
    <span class="icon-checkmark"></span>
  </button>

  <a href="{% url 'dashboards:sucursalFormulario' %}" class="btn btn-danger">
    <span class="icon-cross"></span>
  </a>

  {% else %}
  <button class="btn btn-success">
    <span class="icon-plus6"></span>
  </button>
  {% endif %}
</nav>

templates/formularios/forms/form-sucursal2.html
<!-- Start input -->
<div class="form__group field">
    <input
    type="hidden"
    name="id"
    value="{{sucursal.id}}"
    required/>
    <input
      class="form__field"
      type="text"
      placeholder="nombre"
      name="nombre"
      autocomplete="off"
      value="{{sucursal.nombre}}"
      required
      readonly
    />
    <label for="nombre" class="form__label">
      Nombre
    </label>
  </div>
  <!-- End input -->
  
  <!-- Start input -->
  <div class="form__group field">
    <input
      class="form__field"
      type="text"
      placeholder="compania"
      name="compania"
      list="compania"
      autocomplete="off"
      value="{{sucursal.compania}}"
      required
      readonly
    />
    <label for="compania" class="form__label">
      Compañia
    </label>
      <datalist id="compania">
        {% for compania in companias %}
          <option value="{{compania}}">{{compania}}</option>
        {% endfor %}
      </datalist>
  </div>
  <!-- End input -->
  
  <!-- Start input -->
  <div class="form__group field">
    <input
      class="form__field"
      type="text"
      placeholder="rendimiento-nueva-1r"
      name="rendimiento_de_nueva"
      autocomplete="off"
      value="{{sucursal.rendimiento_de_nueva}}"
      required
    />
    <label for="rendimiento-nueva-1r" class="form__label">
      Rendimiento nueva a 1R
    </label>
  </div>
  <!-- End input -->
  
  <!-- Start input -->
  <div class="form__group field">
    <input
      class="form__field"
      type="text"
      placeholder="rendimiento-1r-2r"
      name="rendimiento_de_primera"
      autocomplete="off"
      value="{{sucursal.rendimiento_de_primera}}"
      required
    />
    <label for="rendimiento-1r" class="form__label">
      Rendimiento 1R a 2R
    </label>
  </div>
  <!-- End input -->
  
  <!-- Start input -->
  <div class="form__group field">
    <input
      class="form__field"
      type="text"
      placeholder="rendimiento-1r-2r"
      name="rendimiento_de_segunda"
      autocomplete="off"
      value="{{sucursal.rendimiento_de_segunda}}"
      required
    />
    <label for="rendimiento-1r" class="form__label">
      Rendimiento 2R a 3R
    </label>
  </div>
  <!-- End input -->
  
  <!-- Start input -->
  <div class="form__group field">
    <input
      class="form__field"
      type="text"
      placeholder="rendimiento-1r-2r"
      name="rendimiento_de_tercera"
      autocomplete="off"
      value="{{sucursal.rendimiento_de_tercera}}"
      required
    />
    <label for="rendimiento-1r" class="form__label">
      Rendimiento 3R a 4R
    </label>
  </div>
  <!-- End input -->
  
  <!-- Start input -->
  <div class="form__group field">
    <input
      class="form__field"
      type="text"
      placeholder="rendimiento-1r-2r"
      name="rendimiento_de_cuarta"
      value="{{sucursal.rendimiento_de_cuarta}}"
      autocomplete="off"
      required
    />
    <label for="rendimiento-1r" class="form__label">
      Rendimiento 4R a 5R
    </label>
  </div>
  <!-- End input -->
  
  <!-- Start input -->
  <div class="form__group field">
    <input
      class="form__field"
      type="text"
      placeholder="precio-promedio-llanta-direccion"
      name="precio_nueva_direccion"
      value="{{sucursal.precio_nueva_direccion}}"
      autocomplete="off"
      required
    />
    <label for="precio-promedio-llanta-direccion" class="form__label">
      Precio promedio llanta dirección
    </label>
  </div>
  <!-- End input -->
  
  <!-- Start input -->
  <div class="form__group field">
    <input
      class="form__field"
      type="text"
      placeholder="precio-promedio-llanta-nueva"
      name="precio_nueva"
      value="{{sucursal.precio_nueva}}"
      autocomplete="off"
      required
    />
    <label for="precio-promedio-llanta-nueva" class="form__label">
      Precio promedio llanta nueva
    </label>
  </div>
  <!-- End input -->
  
  <!-- Start input -->
  <div class="form__group field">
    <input
      class="form__field"
      type="text"
      placeholder="precio-promedio-llanta-renovada"
      name="precio_renovada"
      value="{{sucursal.precio_renovada}}"
      autocomplete="off"
      required
    />
    <label for="precio-promedio-llanta-renovada" class="form__label">
      Precio promedio llanta renovada
    </label>
  </div>
  <!-- End input -->
  

templates/formularios/forms/form-taller.html
<!-- Start input -->
<div class="form__group field">
  <input
    type="hidden"
    name="id"
    {% if taller.id %}value="{{taller.id}}"{% endif %}
  />
  <input
    class="form__field"
    type="text"
    placeholder="nombre"
    name="nombre"
    {% if taller.nombre %}value="{{taller.nombre}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="nombre" class="form__label">
    Nombre
  </label>
</div>
<!-- End input -->

<!-- Start input -->
<!-- <div class="form__group field">
  <input
    class="form__field"
    type="text"
    placeholder="compania"
    name="compania"
    list="compania"
    {% if taller.compania %}value="{{taller.compania}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="compania" class="form__label">
    Compañia
  </label>
  <datalist id="compania">
    {% for compania in companias %}
      <option value="{{compania}}">{{compania}}</option>
    {% endfor %}
  </datalist>
</div> -->
<!-- End input -->

<label for="compania" class="select-label">Compañia</label>
<select name="compania" id="compania" required class="select-input">
  <option value="">Seleccione una compañia...</option>
  {% if taller.compania %}<option value="{{taller.compania}}" selected>{{taller.compania}}</option>{% endif %}
  {% for compania in companias %}
    <option value="{{compania}}">{{compania}}</option>
  {% endfor %}
</select>

<!-- Start input -->
<div class="form__group field">
  <input
    class="form__field"
    type="text"
    placeholder="codigo"
    name="codigo"
    {% if taller.codigo %}value="{{taller.codigo}}"{% endif %}
    autocomplete="off"
    required
  />
  <label for="codigo" class="form__label">
    Código
  </label>
</div>
<!-- End input -->